nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ 'Content-Type', 'Authorization' ]
    expose_headers: [ 'Link' ]
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: [ '*' ]
      allow_headers: [ '*' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
      max_age: 3600
#  defaults:
#    allow_credentials: true
#    allow_origin: [ 'http://localhost:5178', 'http://localhost:5173' ] # Add the required origins here
#    allow_headers: [ '*' ]
#    allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
#    expose_headers: [ ]
#    max_age: 3600
#  paths:
#    '^/': ~